# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "centos/7" 

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'centos7-sig-cicd'
    vb.memory = 4096
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # set up the environment in the new VM:
  # 
  $script = <<-SCRIPT

  # Sleep is necessary because the network is not available right after the start of the VM. All following actions
  # depend heavilly on the network.

  sleep 45

  # Yum actions:
  # - yum update
  # - get all the packages that are needed for creating the AWS environment:
  #   - python3     (for using the SDK to add users to AWS)
  #   - git         (for downloading the repository that is used in the blog)
  #   - zip/unzip   (for unzipping the terraform zip and to zip the lambda functions)
  #   - python3-pip (for pip: this is used to get the newest boto3 version)
  #   - awscli      (for the CLI of AWS, this is used to set the passwords for users, also used to check if the star certificate for your domain already exists - or not)

  yum update -y
  yum install python3 git zip unzip python3-pip awscli -y

  # Download and install terraform version 0.12.24
  # 

  curl https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip --output terraform.zip
  unzip terraform.zip
  rm terraform.zip

  # Install boto3
  #
  pip3 install boto3

  # Get the install script from S3
  curl https://frpublic.s3-eu-west-1.amazonaws.com/AMIS/install+scripts/sig-cicd-init-all.sh --output init-all.sh
  SCRIPT
  
  config.vm.provision "shell",
      inline: $script
	  
end
